#!/bin/bash

#PBS -q mpi_9
#PBS -l walltime=28:00:00
#PBS -eo

module purge
source /usr/share/Modules/3.2.10/init/bash
module load   NETCDF-test/4.3.3.1-mpt217-intel2018
module list

RST=1 # Do a restart

# Experiment path
expt_path=${SCRATCH}/nemo_expt_4.2.0
mkdir -p ${expt_path}

# Move to working directory
cd $expt_path
#source ../functions_pbs.sh # Distrubute file, if I forget, contact josue.mtzmo@gmail.com


# From /home1/datahome/jmartine/models/nemo_4.2.0/tests/MY_ICE_CANAL/EXP_ice_forming/init 
# and  /home1/datahome/jmartine/models/nemo_4.2.0/tests/MY_ICE_CANAL/EXP_ice_forming/forcing
ln -sf /home1/datawork/ctalandi/CHANEL-ICE/ICE-BUG/Channel_Oce_pt_noise_pS_1000_5000_grid_freezing_point_75m_lin_strat_depth_6months.nc .
ln -sf /home1/datawork/ctalandi/CHANEL-ICE/ICE-BUG/Channel-Surf-Forcing_new_ALL_seasonal_new_grid_HR_HTR_out_boundaries_april_center_no_atm_temp_moving.nc .

cp  /home1/datahome/ctalandi/DEV/ICE-CHANNEL/*.xml .
cp  /home1/datahome/ctalandi/DEV/ICE-CHANNEL/namelist* .
if [ ${RST} -eq 1 ] ; then 
	cp  /home1/datahome/ctalandi/DEV/ICE-CHANNEL/namelist_cfg_rst namelist_cfg
	cp  /home1/datahome/ctalandi/DEV/ICE-CHANNEL/namelist_ice_cfg_rst namelist_ice_cfg
fi

ln -sf /home1/datahome/ctalandi/DEV/GITREP/DCM_4.0/DCMTOOLS/NEMOREF/nemo_4.2.0/tests/MY_ICE_CANAL/BLD/bin/nemo.exe .

$MPI_LAUNCH  -np 252 ./nemo.exe  >& ./mpi_model.output

